### ISSUE TITLE
About neurips-2023-data

### ISSUE THREAD

**Issue by 995884191** [openproblems-bio/task_perturbation_prediction#80]
Hi,

I am interested in the benchmark on predicting how small molecules change gene expression in different cell types. However, I couldn't find the file resources/datasets/neurips-2023-data in the repository.

Could you please provide guidance on how to access this dataset? Any assistance would be greatly appreciated!

Thank you!

**Comment by szalata** [comment]
Hello,
Great to hear about your interest in our work!
Note that all the data details will be released with all the NeurIPS2024 papers in a publication titled "A benchmark for prediction of transcriptomic responses to chemical perturbations across cell types".
In the meantime, feel free to download the data from public repositories. Here I copied a part of our data availability paragraph:

> processed counts data is publicly available through the Gene Expression Omnibus (GEO) with accession \href{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE279945}{GSE279945} and raw sequencing data is available through the Sequencing Read Archive (SRA) with accession \href{https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1149320}{PRJNA1149320}.

**Comment by 995884191** [comment]
> Hello, Great to hear about your interest in our work! Note that all the data details will be released with all the NeurIPS2024 papers in a publication titled "A benchmark for prediction of transcriptomic responses to chemical perturbations across cell types". In the meantime, feel free to download the data from public repositories. Here I copied a part of our data availability paragraph:
> 
> > processed counts data is publicly available through the Gene Expression Omnibus (GEO) with accession \href{[https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE279945}{GSE279945}](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE279945%7D%7BGSE279945%7D) and raw sequencing data is available through the Sequencing Read Archive (SRA) with accession \href{[https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1149320}{PRJNA1149320}](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1149320%7D%7BPRJNA1149320%7D).

Thank You!

Dear szalata,

I hope this message finds you well. I wanted to take a moment to express my heartfelt gratitude for your incredible work on perturbation prediction. As a graduate student, I have found your contributions to be extremely inspiring and valuable to my research.

Your timely responses to my questions have greatly helped me navigate some challenges, and I truly appreciate the support you provide to the community. Thank you once again for all your hard work and dedication!

**Comment by szalata** [comment]
Thank you for the kind words! Note that this is a collaborative work with contributions from many authors. We are happy to help!
