### ISSUE TITLE
Metric info is rendered incorrectly on the website

### ISSUE THREAD

**Issue by szalata** [openproblems-bio/task_perturbation_prediction#83]
There appears to be an issue with the metric description:
https://openproblems.bio/results/perturbation_prediction/#ref-article .
Incorrect reference appears repeatedly.

<img width="581" alt="Screenshot 2024-11-20 at 8 47 07 AM" src="https://github.com/user-attachments/assets/60f38b85-5c40-41e7-a4f3-52a3836a1644">

**Comment by KaiWaldrant** [comment]
Already working on that
